name: sweaden_old_new_version
description: Sweaden Broker - better version.
publish_to: 'none'
version: 3.30.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  # android_intent_plus: ^5.3.0
  # animate_do: ^4.2.0
  # back_button_interceptor: ^8.0.4
  # camera: ^0.11.1
  # connectivity_plus: ^6.1.4
  # file_picker: ^10.2.0
  # firebase_core: ^3.15.1
  # firebase_crashlytics: ^4.3.9
  # firebase_messaging: ^15.2.9
  android_intent_plus: ^5.3.0
  animate_do: ^4.2.0
  back_button_interceptor: ^8.0.4
  camera: ^0.11.0+2
  connectivity_plus: ^6.1.4
  file_picker: ^10.2.0
  firebase_core: ^3.15.1
  firebase_crashlytics: ^4.3.9
  firebase_messaging: ^15.2.9
  flutter:
    sdk: flutter
  # flutter_awesome_select_clone: ^7.5.0
  # flutter_background_service: ^5.1.0
  # flutter_google_places_sdk: ^0.4.2+1
  # flutter_image_compress: ^2.4.0
  # flutter_local_notifications: ^19.3.0
  flutter_awesome_select_clone: ^7.5.0
  flutter_background_service: ^5.1.0
  flutter_google_places_sdk: ^0.4.2+1
  flutter_image_compress: ^2.4.0
  flutter_local_notifications: ^19.3.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  geolocator: 12.0.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.1
  google_mlkit_face_detection: ^0.13.1
  http: ^1.4.0
  http_parser: ^4.0.2
  image: ^4.5.4
  image_picker: ^1.1.2
  internet_connection_checker: ^3.0.1
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  logger: ^2.6.0
  modal_bottom_sheet: ^3.0.0
  otp_text_field: ^1.1.3
  package_info_plus: ^8.3.0
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.5
  rounded_loading_button_plus: ^3.0.1
  signature: ^5.5.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  video_compress: ^3.1.4
  video_player: ^2.9.5
  # flutter_secure_storage: ^9.2.4
  # geolocator: ^14.0.2
  # google_fonts: ^6.2.1
  # google_maps_flutter: ^2.12.3
  # google_mlkit_face_detection: ^0.13.1
  # http: ^1.4.0
  # http_parser: ^4.1.2
  # image: ^4.5.4
  # image_picker: ^1.1.2
  # internet_connection_checker: ^3.0.1
  # intl: ^0.19.0
  # jwt_decoder: ^2.0.1
  # logger: ^2.6.0
  # modal_bottom_sheet: ^3.0.0
  # otp_text_field: ^1.1.3
  # package_info_plus: ^8.3.0
  # page_transition: ^2.2.1
  # path_provider: ^2.1.5
  # permission_handler: ^12.0.1
  # provider: ^6.1.5
  # rounded_loading_button_plus: ^3.0.1
  # signature: ^6.3.0
  # url_launcher: ^6.3.1
  # uuid: ^4.5.1
  # video_compress: ^3.1.4
  # video_player: ^2.10.0

dependency_overrides:
  geolocator_android: 4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
