// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkpZtdSSg0nmaBmb3X5SI63iStAlsFsSc',
    appId: '1:364589936912:web:4d87dd0fe0e943cd7e3595',
    messagingSenderId: '364589936912',
    projectId: 'sweaden-7806e',
    authDomain: 'sweaden-7806e.firebaseapp.com',
    databaseURL: 'https://sweaden-7806e.firebaseio.com',
    storageBucket: 'sweaden-7806e.firebasestorage.app',
    measurementId: 'G-Z79HS1WHSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgA69EYJLS6sCfPIv9_r6tM2s_HerW8HQ',
    appId: '1:364589936912:android:b733c65e9290a3557e3595',
    messagingSenderId: '364589936912',
    projectId: 'sweaden-7806e',
    databaseURL: 'https://sweaden-7806e.firebaseio.com',
    storageBucket: 'sweaden-7806e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd3_rHgTLwHlGr2Rj2GSdCRZHuVs14MqQ',
    appId: '1:364589936912:ios:0e4b6de098ac65d67e3595',
    messagingSenderId: '364589936912',
    projectId: 'sweaden-7806e',
    databaseURL: 'https://sweaden-7806e.firebaseio.com',
    storageBucket: 'sweaden-7806e.firebasestorage.app',
    iosBundleId: 'com.example.sweadenOldNewVersion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd3_rHgTLwHlGr2Rj2GSdCRZHuVs14MqQ',
    appId: '1:364589936912:ios:0e4b6de098ac65d67e3595',
    messagingSenderId: '364589936912',
    projectId: 'sweaden-7806e',
    databaseURL: 'https://sweaden-7806e.firebaseio.com',
    storageBucket: 'sweaden-7806e.firebasestorage.app',
    iosBundleId: 'com.example.sweadenOldNewVersion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkpZtdSSg0nmaBmb3X5SI63iStAlsFsSc',
    appId: '1:364589936912:web:9fed36462c8e74a37e3595',
    messagingSenderId: '364589936912',
    projectId: 'sweaden-7806e',
    authDomain: 'sweaden-7806e.firebaseapp.com',
    databaseURL: 'https://sweaden-7806e.firebaseio.com',
    storageBucket: 'sweaden-7806e.firebasestorage.app',
    measurementId: 'G-KCZDZ6ZFF5',
  );
}
